[target.x86_64-unknown-linux-gnu]
rustflags = [
  "-C", "link-arg=-fuse-ld=lld",
  "-C", "target-feature=+aes,+sse2,+ssse3,+sse4.1,+sse4.2"
]
linker = "clang"

[target.x86_64-unknown-linux-musl]
linker = "clang"
rustflags = [
  "-C", "link-arg=-fuse-ld=lld",
  "-C", "target-feature=+aes,+sse2,+ssse3,+sse4.1,+sse4.2"
]

[target.aarch64-unknown-linux-gnu]
linker = "clang"
rustflags = [
  "-C", "link-arg=-fuse-ld=lld",
  "-C", "target-feature=+aes,+neon"
]

[target.aarch64-unknown-linux-musl]
linker = "clang"
rustflags = [
  "-C", "link-arg=-fuse-ld=lld",
  "-C", "target-feature=+aes,+neon"
]

[target.aarch64-apple-darwin]
rustflags = ["-C", "target-feature=+aes,+neon"]

[target.x86_64-apple-darwin]
rustflags = ["-C", "target-feature=+aes,+sse2,+ssse3,+sse4.1,+sse4.2"]

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+aes,+sse2,+ssse3,+sse4.1,+sse4.2"]
